---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitec-user-service-frontend-deploy 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: thapeloseema/capitec-user-service:frontend-amd64
          ports:
            - containerPort: 4200