apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitec-user-service-backend-deploy
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thapeloseema/capitec-user-service:backend-amd64
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgres://postgres:5432/postgres"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "postgres"