---
apiVersion: v1
kind: Service
metadata:
  name: capitec-user-service-frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer